In [22]:
import numpy as np
from datetime import datetime

np.random.seed(0)

In [23]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [24]:
def sigmoid(z):
  return 1/ (1+np.exp(-z))

In [38]:
x_data = np.array([[0,0], [0,1],[1,0],[1,1]])   
t_data = np.array([0, 1, 1, 0]).reshape(4,1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (4, 2) , t_data.shape =  (4, 1)


In [39]:
W = np.random.rand(2,1)  
b = np.random.rand(1)  

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.64589411]
 [0.43758721]] , W.shape =  (2, 1) , b =  [0.891773] , b.shape =  (1,)


In [40]:
def loss_func(x, t):
    
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  (-np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) ) )
    
    #return ( np.sum( (t - y)**2 ) ) / ( len(x) )

In [41]:
def error_val(x, t):
    #delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    #return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) ) 
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

In [42]:
learning_rate = 1e-5  # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data,t_data)  

print("Initial error value = ", error_val(x_data, t_data) )

start_time = datetime.now()

for step in  range(200001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 5000 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data) )
        
end_time = datetime.now()
        
print("")
print("Elapsed Time => ", end_time - start_time)


Initial error value =  0.3373276867202459
step =  0 error value =  0.337326169038785
step =  5000 error value =  0.3298446565436006
step =  10000 error value =  0.32261801914544375
step =  15000 error value =  0.3157027453333967
step =  20000 error value =  0.3091467432020053
step =  25000 error value =  0.302987791115381
step =  30000 error value =  0.2972526930672792
step =  35000 error value =  0.2919571594045587
step =  40000 error value =  0.28710634679528424
step =  45000 error value =  0.2826959261056028
step =  50000 error value =  0.2787135112992389
step =  55000 error value =  0.27514027667862817
step =  60000 error value =  0.27195260774458735
step =  65000 error value =  0.269123663658822
step =  70000 error value =  0.2666247676774055
step =  75000 error value =  0.2644265787960108
step =  80000 error value =  0.262500028697594
step =  85000 error value =  0.260817030960207
step =  90000 error value =  0.2593509843300525
step =  95000 error value =  0.2580770998179688
step

In [33]:
# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 test_data : numpy type
def predict(test_data):
    
    z = np.dot(test_data, W) + b
    y = sigmoid(z)
    
    if y >= 0.5:
        result = 1  # True
    else:
        result = 0  # False
    
    return y, result

In [45]:
test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

(real_val, logical_val) = predict(test_data)

print(real_val, logical_val)

ValueError: ignored

In [46]:
test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for input_data in test_data:

    print(predict(input_data))

(array([0.50769011]), 1)
(array([0.49976809]), 0)
(array([0.53253619]), 1)
(array([0.52463962]), 1)
